baseURL = "https://apmath-spbu.github.io/"
languageCode = "ru-ru"
defaultContentLanguage = "ru"

title = "Краткий курс по основам программирования"
# theme = "hugo-theme-learn"
theme = "hugo-theme-relearn"
disqusShortname = "username" # delete this to disable disqus comments
sectionPagesMenu = "main"

[markup]
  [markup.highlight]
    lineNos = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      # unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[params]
  #editURL = "https://apmath-spbu.github.io/"
  # description = "Материалы курсов на кафедре Технологии Программирования. ПМ-ПУ"
  # author = "Alexander Ulanov"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  # disableMermaid = false
  # customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"
  themeVariant = "green"
  math = true
  defaultContentSort = "weight"
  # enableEmoji = true
  [[params.boxStyle]]
    color = 'blue'
    i18n = ''
    icon = 'rainbow'
    identifier = 'def'
    title = 'Определение'
  [[params.boxStyle]]
    color = 'green'
    i18n = ''
    icon = 'shapes'
    identifier = 'theorem'
    title = 'Теорема'
  [[params.boxStyle]]
    color = 'purple'
    i18n = ''
    icon = 'horse'
    identifier = 'lemma'
    title = 'Лемма'
  [[params.boxStyle]]
    color = 'gray'
    i18n = ''
    icon = 'lock-open'
    identifier = 'prove'
    title = 'Доказательство'
  [[params.boxStyle]]
    color = 'gray'
    i18n = ''
    icon = 'chart-gantt'
    identifier = 'props'
    title = 'Свойства'
  [[params.boxStyle]]
    color = 'green'
    i18n = ''
    icon = 'chart-gantt'
    identifier = 'ex'
    title = 'Пример'
  [[params.boxStyle]]
    color = 'green'
    i18n = ''
    icon = 'chart-gantt'
    identifier = 'corollar'
    title = 'Следствие'
  [[params.boxStyle]]
    color = 'pink'
    i18n = ''
    icon = 'palette'
    identifier = 'offer'
    title = 'Предложение'

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

#[[menu.icon]]
#    url = "mailto:me@example.com"
#    name = "envelope-o"
#    weight = 1

#[[menu.icon]]
#    url = "https://github.com/username/"
#    name = "github"
#    weight = 2

#[[menu.icon]]
#    url = "https://twitter.com/username/"
#    name = "twitter"
#    weight = 3

#[[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
#    name = "linkedin"
#    weight = 4

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#    weight = 5
