baseURL = "https://apmath-spbu.github.io/"
languageCode = "ru-ru"
defaultContentLanguage = "ru"

title = "Материалы курсов на кафедре Технологии Программирования. ПМ-ПУ"
theme = "hugo-theme-learn"
disqusShortname = "username" # delete this to disable disqus comments
sectionPagesMenu = "main"

[params]
  #editURL = "https://apmath-spbu.github.io/"
  description = "Материалы курсов на кафедре Технологии Программирования. ПМ-ПУ"
  author = "Alexander Ulanov"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"
  themeVariant = "green"
  

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

#[[menu.icon]]
#    url = "mailto:me@example.com"
#    name = "envelope-o"
#    weight = 1

#[[menu.icon]]
#    url = "https://github.com/username/"
#    name = "github"
#    weight = 2

#[[menu.icon]]
#    url = "https://twitter.com/username/"
#    name = "twitter"
#    weight = 3

#[[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
#    name = "linkedin"
#    weight = 4

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#    weight = 5
